/**:
  ros__parameters:
    input_sources: ['kinect', 'xsens']

    translation_ids:
      # PELVIS
      kinect: [0]
      xsens:  [1]

    rotation_ids:
      # PELVIS, SHOULDER_RIGHT, ELBOW_RIGHT, WRIST_RIGHT, SHOULDER_LEFT, ELBOW_LEFT, WRIST_LEFT,
      # HIP_RIGHT, KNEE_RIGHT, ANKLE_RIGHT, HIP_LEFT, KNEE_LEFT, ANKLE_LEFT
      kinect: [0, 12, 13, 14,  5,  6,  7, 22, 23, 24, 18, 19, 20]
      xsens:  [1,  9, 10, 11, 13, 14, 15, 16, 17, 18, 20, 21, 22]
